version: '3'

services:
 cprabbit:
  image: 666pehid666/crazy-rabbitmq:latest
  ports:
   - 5672:5672
   - 15672:15672
  networks:
   - mailnet
   - backend

 mailsender:
  image: 666pehid666/crazy-mailsender:latest
  ports:
   - 7000:80
  networks:
   - mailnet

 identityserver:
  image: 666pehid666/crazy-identity:latest
  ports:
   - 8001:443
   - 8000:80
  networks:
   - backend

 webapi:
  image: 666pehid666/crazy-api:latest
  ports:
   - 9001:443
   - 9000:80
  networks:
   - backend
  depends_on:
   - identityserver

networks:
  backend:
  mailnet: